version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
     - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.13-2.7.0
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092, OUTSIDE://10.252.73.143:9093 # pc ip
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092, OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - ./var/run/docker.sock:/var/run/docker.sock

  receiver:
    container_name: receiver
    image: seol0keti/ubuntu:1.1
    command: /bin/bash
    stdin_open: true
    tty: true
    ports:
      - "7980:7980"
    expose: 
      - "7980"

  preprocessor:
    container_name: preprocessor
    image: seol0keti/ubuntu:1.1
    command: /bin/bash
    stdin_open: true
    tty: true
    
  redis:
    container_name: redis
    image: redis:6.2
    expose: 
      - "6379"
