version: '3'
services:
  influxdb:
    image: influxdb:1.8
    container_name: influx
    restart: always
    environment:
      - INFLUXDB_DB=dbclass
    expose: 
      - "8086"
    ports:
      - 8086:8086
    volumes:
      - /docker/influx/data:/var/lib/influx/data