version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
     - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092, OUTSIDE://10.252.73.143:9093 # pc ip
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092, OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - ./var/run/docker.sock:/var/run/docker.sock

  receiver:
    image: seol0keti/ubuntu:1.1
    container_name: receiver
    command: /bin/bash
    stdin_open: true
    tty: true
    ports:
      - "7980:7980"
    expose: 
      - "7980"

  preprocessor:
    image: seol0keti/ubuntu:1.1
    container_name: preprocessor
    restart: always
    command: /bin/bash
    stdin_open: true
    tty: true
    
  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    expose: 
      - "6379"

  influxdb:
    image: influxdb:1.8
    container_name: influx
    restart: always
    environment:
      - INFLUXDB_DB=dbclass
    expose: 
      - "8086"
    ports:
      - 8086:8086
    volumes:
      - /docker/influx/data:/var/lib/influx/data